### ISSUE TITLE
Issues working with powershell

### ISSUE THREAD

**Issue by infosatheesh2020** [yangl900/azshell#2]
After adding the windows binary in the PATH variable, it works in cmd prompt, but PowerShell window gets stuck with error "NativeCommandError"
![ps](https://user-images.githubusercontent.com/11145865/57752388-a5ff6c80-7706-11e9-8526-4739c0fe974d.jpg)

**Comment by yangl900** [comment]
thanks for reporting! I haven't get chance to test it on windows powershell. I found this discussion: https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide

It suggested a workaround to redirect stderr, by 
```powershell
du 2> $null
```

**Comment by infosatheesh2020** [comment]
@yangl900 BTW, it is not about just some additional error, but the actual functionality doesn't work in ISE. The window gets struck after that. It never launches cloud shell prompt.

**Comment by yangl900** [comment]
Got it. I have not tested it on ISE. Regular PowerShell window or CMD should be fine.

**Comment by infosatheesh2020** [comment]
Got it, thanks
