### ISSUE TITLE
websocket: must provide an address to connect to

### ISSUE THREAD

**Issue by jbpaux** [yangl900/azshell#3]
Hello,

I've downloaded and executed azshell on Windows 10 x64.
After authentication, I select my AAD tenant then I've got these ouputs:
2019/05/16 14:08:41 Requesting Cloud Shell...
2019/05/16 14:08:41 Succeeded.
2019/05/16 14:08:41 Connecting terminal...
2019/05/16 14:08:41 websocket: must provide an address to connect to

Can you advise what's wrong ?
I don't use any proxy.

**Comment by yangl900** [comment]
thanks! I believe it is because you haven't setup your account with cloud shell yet. If you go to https://shell.azure.com it should prompt you to setup. Once it is setup, you shouldn't see this error anymore. I do need better error handling in this case though.

**Comment by yangl900** [comment]
should be fixed by commit d8a59bdf047e3cfeab458c9d539ee12959c829ae

**Comment by yangl900** [comment]
Should be fixed with the new released binary (v0.2.1). Please let me know if you still hit this issue.

**Comment by jbpaux** [comment]
Yes ! It's working great !
